# Generated by Django 5.1.7 on 2025-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='rtl',
            field=models.BooleanField(default=False),
        ),
    ]
